Repository ESGI-69/challenge-flutter-go, pull requests merged in 2024-06, with the labels that each got.

#50 47 create chat message endpoints
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/chatMessage.go
  go/api/handlers/note.go
  go/api/requests/chatMessage.go
  go/api/responses/chatMessage.go
  go/api/responses/note.go
  go/api/server.go
  go/database/database.go
  go/models/chatMessage.go
  go/repository/chatMessage.go
  go/repository/note.go
Labels: go

#51 Add meeting point on transport
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/transport.go
  go/api/requests/transport.go
  go/api/responses/transport.go
  go/api/server.go
  go/models/transport.go
  go/models/trip.go
  go/repository/transport.go
  go/repository/trip.go
Labels: go

#60 57 list the user trips on home page
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/app.dart
Labels: flutter

#68 66 create the trip page header
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Home/trip_card.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Button/button_back.dart
  move_together_app/lib/Widgets/Participant/participant_icon.dart
  move_together_app/lib/Widgets/Participant/participant_icons.dart
  move_together_app/lib/Widgets/Trip/trip_app_bar.dart
  move_together_app/lib/Widgets/Trip/trip_card.dart
  move_together_app/lib/Widgets/Trip/trip_quick_info.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/trip/join_screen.dart
  move_together_app/lib/views/trip/trip_screen.dart
Labels: flutter

#71 Harmonize the Trip Quick Info
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/trip.go
  go/api/requests/trip.go
  go/models/trip.go
  go/repository/trip.go
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Trip/trip_app_bar.dart
  move_together_app/lib/Widgets/Trip/trip_card.dart
  move_together_app/lib/Widgets/Trip/trip_quick_info.dart
Labels: flutter, go

#73 63 leave a trip with a confirm modal
  move_together_app/lib/Home/blocs/home_bloc.dart
  move_together_app/lib/Home/blocs/home_event.dart
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Widgets/Button/button_leave.dart
  move_together_app/lib/Widgets/Trip/trip_card.dart
  move_together_app/lib/app.dart
  move_together_app/lib/core/models/participant.dart
  move_together_app/lib/core/models/trip.dart
  move_together_app/lib/core/services/api_services.dart
  move_together_app/lib/router.dart
  move_together_app/lib/utils/show_unified_dialog.dart
Labels: flutter

#78 feat(Trips): add delete trip button & endpoint
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/trip.go
  go/api/server.go
  go/repository/trip.go
  move_together_app/lib/Home/blocs/home_bloc.dart
  move_together_app/lib/Home/blocs/home_event.dart
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_card.dart
  move_together_app/lib/Trip/trip_quick_info.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Button/button_delete.dart
  move_together_app/lib/core/services/api_services.dart
Labels: flutter, go

#69 43 API endpoint pour l'upload de document sur un trip
  .github/CODEOWNERS
  go/.gitignore
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/document.go
  go/api/requests/document.go
  go/api/responses/document.go
  go/api/server.go
  go/api/utils/filesHandler.go
  go/database/database.go
  go/models/document.go
  go/repository/document.go
  k8s/backend-all.yaml
Labels: go

#81 feat(Document): Make document desciprtion optional
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/document.go
Labels: bug, go

#83 Trip edit name
  go/api/handlers/trip.go
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/bloc/trip_event.dart
  move_together_app/lib/Trip/bloc/trip_state.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_quick_info.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Dialog/edit_trip_name.dart
  move_together_app/lib/core/services/api_services.dart
  move_together_app/lib/router.dart
Labels: flutter

#79 33 implements blocs archi in flutter
  go/go.mod
  go/go.sum
  move_together_app/lib/Home/blocs/home_bloc.dart
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Profile/bloc/profile_bloc.dart
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Provider/auth_provider.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/trip_card.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/core/models/participant.dart
  move_together_app/lib/core/models/trip.dart
  move_together_app/lib/core/services/api_services.dart
  move_together_app/lib/main.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/login_screen.dart
  move_together_app/lib/views/register_screen.dart
  move_together_app/lib/views/trip/join_screen.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: flutter

#91 Add trip feature card & transport
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Transport/bloc/transport_bloc.dart
  move_together_app/lib/Transport/bloc/transport_event.dart
  move_together_app/lib/Transport/bloc/transport_state.dart
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_body.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Card/trip_feature_card.dart
  move_together_app/lib/core/models/transport.dart
  move_together_app/lib/core/models/user.dart
  move_together_app/lib/core/services/api_services.dart
Labels: flutter

#82 40 create trip page flutter
  move_together_app/README.md
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/bloc/trip_event.dart
  move_together_app/lib/Widgets/Input/cool_text_field.dart
  move_together_app/lib/core/services/api_services.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/trip/create_screen.dart
  move_together_app/lib/views/trip/join_screen.dart
Labels: flutter

#103 fix(UserCreation): adding new validation constraint in deserialization
  go/api/requests/user.go
  go/api/utils/deserializer.go
Labels: bug, go

#99 Dio implem
  move_together_app/lib/Home/blocs/home_bloc.dart
  move_together_app/lib/Profile/bloc/profile_bloc.dart
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Provider/auth_provider.dart
  move_together_app/lib/Transport/bloc/transport_bloc.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/trip_join_screen.dart
  move_together_app/lib/core/models/trip.dart
  move_together_app/lib/core/services/api.dart
  move_together_app/lib/core/services/api_services.dart
  move_together_app/lib/core/services/auth_service.dart
  move_together_app/lib/core/services/transport_service.dart
  move_together_app/lib/core/services/trip_service.dart
  move_together_app/lib/core/services/user_service.dart
  move_together_app/lib/views/login_screen.dart
  move_together_app/lib/views/register_screen.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: flutter

#105 44 log errors
  go/.gitignore
  go/api/errorHandlers/gin.go
  go/api/errorHandlers/gorm.go
  go/api/handlers/accommodation.go
  go/api/handlers/auth.go
  go/api/handlers/chatMessage.go
  go/api/handlers/document.go
  go/api/handlers/note.go
  go/api/handlers/participant.go
  go/api/handlers/transport.go
  go/api/handlers/trip.go
  go/api/handlers/user.go
  go/api/middlewares/auth.go
  go/api/middlewares/tripPermission.go
  go/api/server.go
  go/database/database.go
  go/logger/api.go
  go/logger/logger.go
  go/models/logEntry.go
  k8s/backend-all.yaml
Labels: go

#109 108 uploads logs are created at root level inside the container instead at app level
  go/Dockerfile
  go/logger/logger.go
  k8s/backend-all.yaml
Labels: bug, go, ci/k8s

#110 feat(edit-date-ontap): add date edit on trip page, add onDateTap/onDa…
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_quick_info.dart
  move_together_app/lib/Trip/trip_screen.dart
Labels: flutter

#96 76 chat real time
  go/api/handlers/chatMessage.go
  go/api/handlers/socket.go
  go/api/server.go
  go/go.mod
  go/go.sum
  move_together_app/lib/Chat/bloc/chat_bloc.dart
  move_together_app/lib/Chat/bloc/chat_event.dart
  move_together_app/lib/Chat/bloc/chat_state.dart
  move_together_app/lib/Chat/chat_body.dart
  move_together_app/lib/Chat/chat_bubble.dart
  move_together_app/lib/Chat/chat_input.dart
  move_together_app/lib/Chat/chat_screen.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Button/button_chat.dart
  move_together_app/lib/core/models/message.dart
  move_together_app/lib/core/models/user.dart
  move_together_app/lib/core/services/chat_service.dart
  move_together_app/lib/core/services/trip_service.dart
  move_together_app/lib/core/services/websocket_service.dart
  move_together_app/lib/router.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: flutter
