Repository ESGI-69/challenge-flutter-go, pull requests merged in 2024-07, with the labels that each got.

#115 111 fix apk is unable to communicate with api
  go/api/handlers/socket.go
  k8s/ingress.yaml
  move_together_app/.env.example
  move_together_app/.env.release
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_quick_info.dart
  move_together_app/lib/core/services/api.dart
  move_together_app/lib/core/services/auth_service.dart
Labels: flutter

#104 fix(UserCreation): check if username already exists
  go/api/errorHandlers/gorm.go
  go/api/handlers/user.go
  go/api/utils/customValidator.go
  go/api/utils/deserializer.go
  go/database/database.go
  go/go.mod
  go/go.sum
Labels: bug, go

#114 Don't show edit pop up when no perm
  move_together_app/lib/Trip/trip_quick_info.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/core/models/trip.dart
  move_together_app/lib/core/services/api.dart
Labels: bug, flutter

#126 fix: add internet permission to app
  move_together_app/android/app/src/main/AndroidManifest.xml
Labels: flutter

#128 Add the transport create modal
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Transport/transport_create_modal.dart
  move_together_app/lib/Transport/transport_row.dart
  move_together_app/lib/Widgets/Input/cool_date_picker.dart
  move_together_app/lib/Widgets/Input/cool_text_field.dart
  move_together_app/lib/app.dart
  move_together_app/lib/core/models/transport.dart
  move_together_app/lib/core/services/transport_service.dart
Labels: flutter

#130 Add transport info & deletion modal
  go/api/handlers/transport.go
  go/api/server.go
  go/models/transport.go
  go/repository/transport.go
  move_together_app/lib/Transport/bloc/transport_event.dart
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Transport/transport_create_modal.dart
  move_together_app/lib/Transport/transport_info_modal.dart
  move_together_app/lib/Transport/transport_row.dart
  move_together_app/lib/Trip/trip_body.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Card/trip_feature_card.dart
  move_together_app/lib/core/models/message.dart
  move_together_app/lib/core/models/user.dart
  move_together_app/lib/core/services/transport_service.dart
Labels: flutter

#132 Profile page
  move_together_app/lib/Profile/profile_screen.dart
Labels: flutter, go

#133 101 reload trip list on page load
  move_together_app/analysis_options.yaml
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/bloc/trip_event.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_create_screen.dart
  move_together_app/lib/Trip/trip_join_screen.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Button/button_chat.dart
  move_together_app/lib/app.dart
  move_together_app/lib/core/services/trip_service.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/login_screen.dart
Labels: bug, flutter

#129 65 make the app compatible with website
  .github/workflows/flutter.yaml
  go/.env.example
  go/api/server.go
  go/config/config.go
  go/go.mod
  go/go.sum
  k8s/backend-all.yaml
  k8s/config-map.yaml
  move_together_app/.metadata
  move_together_app/lib/Backoffice/Dashboard/dashboard_screen.dart
  move_together_app/lib/Backoffice/Logs/logs_screen.dart
  move_together_app/lib/Backoffice/Trip/trip_screen.dart
  move_together_app/lib/Backoffice/Widgets/navigation_bar_backoffice.dart
  move_together_app/lib/Provider/auth_provider.dart
  move_together_app/lib/backoffice.dart
  move_together_app/lib/core/services/auth_service.dart
  move_together_app/lib/main.dart
  move_together_app/lib/router.dart
  move_together_app/web/index.html
Labels: flutter

#137 Make golang serve the backoffice
  .github/workflows/deploy_go.yaml
  .github/workflows/flutter.yaml
  .github/workflows/go.yaml
  .github/workflows/pr.yaml
  go/.gitignore
  go/Dockerfile
  go/api/server.go
Labels: flutter, go, ci/k8s

#113 feat(getImageFromAddress): add googleMapsWrapper file in utils
  go/.env.example
  go/.gitignore
  go/api/handlers/trip.go
  go/api/server.go
  go/api/utils/downloadGmapImage.go
  go/api/utils/filesHandler.go
  go/api/utils/googleMapsWrapper.go
  go/assets/default.jpg
  go/config/config.go
  go/go.mod
  go/go.sum
  go/models/trip.go
  k8s/backend-all.yaml
  k8s/secrets.yaml
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/core/models/trip.dart
Labels: go

#138 Ajout d'un participant et édition des roles
  .github/workflows/deploy_go.yaml
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/participant.go
  go/api/responses/participant.go
  go/api/server.go
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Participant/bloc/participant_bloc.dart
  move_together_app/lib/Participant/bloc/participant_event.dart
  move_together_app/lib/Participant/bloc/participant_state.dart
  move_together_app/lib/Participant/participant_add_modal.dart
  move_together_app/lib/Participant/participant_row.dart
  move_together_app/lib/Participant/participant_screen.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_card.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/Widgets/Participant/participant_icon.dart
  move_together_app/lib/Widgets/Participant/participant_icons.dart
  move_together_app/lib/app.dart
  move_together_app/lib/core/models/participant.dart
  move_together_app/lib/core/models/trip.dart
  move_together_app/lib/core/services/participant_service.dart
  move_together_app/lib/router.dart
Labels: flutter

#143 139 auto create admin user
  go/database/database.go
  go/models/user.go
Labels: go

#144 fix(chat): parse user role to string
  move_together_app/lib/core/models/user.dart
Labels: bug, flutter

#147 Fix the Dashboard button on backoffice
  move_together_app/lib/router.dart
Labels: bug, flutter

#150 feat(accommodation-card): add accommodation models, service and bloc …
  move_together_app/lib/Accommodation/accommodation_card.dart
  move_together_app/lib/Accommodation/accommodation_create_modal.dart
  move_together_app/lib/Accommodation/accommodation_info_modal.dart
  move_together_app/lib/Accommodation/accommodation_row.dart
  move_together_app/lib/Accommodation/bloc/accommodation_bloc.dart
  move_together_app/lib/Accommodation/bloc/accommodation_event.dart
  move_together_app/lib/Accommodation/bloc/accommodation_state.dart
  move_together_app/lib/Trip/trip_body.dart
  move_together_app/lib/core/models/accommodation.dart
  move_together_app/lib/core/services/accommodation_service.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: flutter

#149 90 photos card upload and display
  .github/workflows/deploy_go.yaml
  .github/workflows/flutter_release.yaml
  .github/workflows/pr.yaml
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/photo.go
  go/api/responses/photo.go
  go/api/server.go
  go/repository/photo.go
  move_together_app/android/app/src/main/AndroidManifest.xml
  move_together_app/ios/Podfile.lock
  move_together_app/ios/Runner/Info.plist
  move_together_app/lib/Photo/bloc/photo_bloc.dart
  move_together_app/lib/Photo/bloc/photo_event.dart
  move_together_app/lib/Photo/bloc/photo_state.dart
  move_together_app/lib/Photo/photo_card.dart
  move_together_app/lib/Photo/photo_info.dart
  move_together_app/lib/Photo/photo_item.dart
  move_together_app/lib/Photo/photo_screen.dart
  move_together_app/lib/Provider/auth_provider.dart
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_body.dart
  move_together_app/lib/Trip/trip_card.dart
  move_together_app/lib/Widgets/Card/trip_feature_card.dart
  move_together_app/lib/Widgets/modal_bottom_sheet_header.dart
  move_together_app/lib/core/models/photo.dart
  move_together_app/lib/core/services/auth_service.dart
  move_together_app/lib/core/services/photo_service.dart
  move_together_app/lib/router.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: flutter, go

#155 154 use new bottom sheet modal everywhere
  move_together_app/lib/Accommodation/accommodation_card.dart
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Participant/participant_info.dart
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/bloc/trip_event.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/router.dart
Labels: flutter

#145 117 backoffice on web
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/trip.go
  go/api/middlewares/admin.go
  go/api/server.go
  go/models/user.go
  go/repository/trip.go
  move_together_app/lib/Backoffice/Trip/bloc/trips_bloc.dart
  move_together_app/lib/Backoffice/Trip/bloc/trips_event.dart
  move_together_app/lib/Backoffice/Trip/bloc/trips_state.dart
  move_together_app/lib/Backoffice/Trip/trip_screen.dart
  move_together_app/lib/Backoffice/Trip/trips_table.dart
  move_together_app/lib/core/services/admin_service.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/login_screen.dart
Labels: go

#158 replace bottom navigation bar by a simple button on app bar
  move_together_app/ios/Podfile.lock
  move_together_app/lib/Chat/chat_screen.dart
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/app.dart
  move_together_app/lib/router.dart
Labels: bug, flutter

#157 feat(ci): add cache to docker build
  .github/workflows/deploy_go.yaml
  .github/workflows/pr.yaml
Labels: go, ci/k8s

#176 feat(feature flipping): backend of feature flipping
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/feature.go
  go/api/requests/feature.go
  go/api/responses/feature.go
  go/api/server.go
  go/database/database.go
  go/models/feature.go
  go/repository/feature.go
Labels: go

#187 Add geopoints to transport and show them on the map, also refactor map
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/accommodation.go
  go/api/handlers/activity.go
  go/api/handlers/transport.go
  go/api/responses/transport.go
  go/api/utils/geo/addressResolver.go
  go/models/accommodation.go
  go/models/activity.go
  go/models/transport.go
  move_together_app/assets/images/pins/meeting_pin.png
  move_together_app/lib/Accommodation/accommodation_create_modal.dart
  move_together_app/lib/Activity/activity_create_modal.dart
  move_together_app/lib/Document/document_create_modal.dart
  move_together_app/lib/Map/bloc/map_bloc.dart
  move_together_app/lib/Map/map_card.dart
  move_together_app/lib/Map/map_screen.dart
  move_together_app/lib/Note/note_create_modal.dart
  move_together_app/lib/Transport/transport_create_modal.dart
  move_together_app/lib/core/models/accommodation.dart
  move_together_app/lib/core/models/activity.dart
  move_together_app/lib/core/models/transport.dart
  move_together_app/lib/core/services/transport_service.dart
  move_together_app/lib/utils/map.dart
Labels: flutter, go

#189 add total price to trip info & refresh trip on change
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/trip.go
  go/api/responses/trip.go
  go/api/server.go
  go/models/trip.go
  move_together_app/lib/Accommodation/accommodation_card.dart
  move_together_app/lib/Activity/activity_card.dart
  move_together_app/lib/Home/blocs/home_bloc.dart
  move_together_app/lib/Home/blocs/home_event.dart
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Trip/bloc/trip_bloc.dart
  move_together_app/lib/Trip/bloc/trip_event.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_body.dart
  move_together_app/lib/Trip/trip_card.dart
  move_together_app/lib/Trip/trip_cost_tag.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/core/models/trip.dart
Labels: flutter, go

#190 Add map & detail to entities infos
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/document.go
  go/api/handlers/note.go
  go/api/responses/document.go
  go/models/document.go
  go/repository/document.go
  move_together_app/lib/Accommodation/accommodation_card.dart
  move_together_app/lib/Accommodation/accommodation_info_modal.dart
  move_together_app/lib/Accommodation/accommodation_screen.dart
  move_together_app/lib/Activity/activity_card.dart
  move_together_app/lib/Activity/activity_info_modal.dart
  move_together_app/lib/Activity/activity_screen.dart
  move_together_app/lib/Document/document_card.dart
  move_together_app/lib/Document/document_info_modal.dart
  move_together_app/lib/Document/document_screen.dart
  move_together_app/lib/Note/note_card.dart
  move_together_app/lib/Note/note_info_modal.dart
  move_together_app/lib/Note/note_screen.dart
  move_together_app/lib/Photo/photos_screen.dart
  move_together_app/lib/Transport/transport_card.dart
  move_together_app/lib/Transport/transport_info_modal.dart
  move_together_app/lib/Transport/transport_screen.dart
  move_together_app/lib/core/models/document.dart
  move_together_app/lib/core/models/note.dart
  move_together_app/lib/router.dart
  move_together_app/lib/utils/map.dart
Labels: flutter, go

#192 fix: pass gin to release mode
  k8s/config-map.yaml
Labels: go, ci/k8s

#199 171 change own user password
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/user.go
  go/api/requests/user.go
  go/api/server.go
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Widgets/details_list.dart
  move_together_app/lib/core/services/user_service.dart
  move_together_app/lib/router.dart
Labels: flutter, go

#214 fix: activity feature
  go/api/handlers/trip.go
  go/database/database.go
  go/models/feature.go
Labels: bug, go

#218 fix: assets
  go/Dockerfile
Labels: go, ci/k8s

#202 168 backoffice logs display filter by level
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/log.go
  go/api/responses/log.go
  go/api/server.go
  go/repository/log.go
  move_together_app/lib/Backoffice/Logs/bloc/logs_bloc.dart
  move_together_app/lib/Backoffice/Logs/bloc/logs_event.dart
  move_together_app/lib/Backoffice/Logs/bloc/logs_state.dart
  move_together_app/lib/Backoffice/Logs/logs_screen.dart
  move_together_app/lib/Backoffice/Logs/logs_table.dart
  move_together_app/lib/core/models/log.dart
  move_together_app/lib/core/services/admin_service.dart
Labels: flutter, go

#225 feat(empty-home): add buttons to create/join a trip on home + landing…
  move_together_app/assets/images/empty_bg.png
  move_together_app/lib/Home/empty_home.dart
Labels: flutter

#229 212 hide trip feature flipping
  go/api/handlers/feature.go
  go/api/middlewares/feature.go
  go/api/server.go
  go/repository/feature.go
Labels: go

#231 223 make the app not compatible with screen rotation
  move_together_app/android/app/src/main/AndroidManifest.xml
  move_together_app/ios/Runner/Info.plist
Labels: bug, flutter

#233 feat(trip): locate on trip creation & center map
  go/api/docs/docs.go
  go/api/docs/swagger.json
  go/api/docs/swagger.yaml
  go/api/handlers/trip.go
  go/api/responses/trip.go
  go/models/trip.go
  move_together_app/lib/Map/map_card.dart
  move_together_app/lib/Trip/trip_body.dart
  move_together_app/lib/core/models/trip.dart
  move_together_app/lib/utils/map.dart
Labels: flutter, go

#235 209 refresh on max scroll top on a trip page
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Trip/trip_screen.dart
Labels: flutter

#238 Fix(photos): disable photo screen when no photos + on delete photos
  move_together_app/lib/Photo/photo_card.dart
  move_together_app/lib/Photo/photos_screen.dart
Labels: flutter

#237 fix(trip): dont bloc the trip creation when the trip image finder is not found
  go/models/trip.go
Labels: go

#246 195 add camera possiblity when we can upload a picture
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Photo/photo_card.dart
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Widgets/bottom_sheet_buttons.dart
  move_together_app/lib/utils/photo_picker.dart
Labels: flutter

#242 feat(chat bubble): add user icon next to chat bubble
  move_together_app/lib/Chat/chat_bubble.dart
  move_together_app/lib/core/models/participant.dart
Labels: flutter

#249 247 app crash when to mutch image are loaded in ram
  move_together_app/lib/Photo/photo_info.dart
  move_together_app/lib/Photo/photo_item.dart
  move_together_app/lib/Profile/bloc/profile_bloc.dart
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Trip/trip_card.dart
  move_together_app/lib/Widgets/Participant/participant_icon.dart
  move_together_app/lib/views/landing_screen.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: bug, flutter

#243 feat(button): use our button everywhere
  move_together_app/lib/Accommodation/accommodation_create_modal.dart
  move_together_app/lib/Accommodation/accommodation_screen.dart
  move_together_app/lib/Activity/activity_create_modal.dart
  move_together_app/lib/Activity/activity_screen.dart
  move_together_app/lib/Backoffice/Logs/logs_screen.dart
  move_together_app/lib/Backoffice/Trip/trips_table.dart
  move_together_app/lib/Document/document_create_modal.dart
  move_together_app/lib/Document/document_screen.dart
  move_together_app/lib/Home/empty_home.dart
  move_together_app/lib/Note/note_create_modal.dart
  move_together_app/lib/Note/note_screen.dart
  move_together_app/lib/Transport/transport_create_modal.dart
  move_together_app/lib/Transport/transport_screen.dart
  move_together_app/lib/Trip/trip_create_screen.dart
  move_together_app/lib/Trip/trip_join_screen.dart
  move_together_app/lib/Widgets/button.dart
  move_together_app/lib/Widgets/details_list.dart
  move_together_app/lib/views/login_screen.dart
Labels: flutter

#254 fix(screen logo): better logic in landing screen + better logo + logo…
  move_together_app/assets/images/fond_couleurs_flou.png
  move_together_app/lib/Widgets/Input/cool_text_field.dart
  move_together_app/lib/Widgets/logo_area.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/landing_screen.dart
  move_together_app/lib/views/login_screen.dart
  move_together_app/lib/views/register_screen.dart
Labels: flutter

#255 feat(qrcode): add qr code scanner and generator to the participant an…
  move_together_app/ios/Podfile.lock
  move_together_app/lib/Chat/chat_screen.dart
  move_together_app/lib/Map/map_screen.dart
  move_together_app/lib/Participant/participant_add_modal.dart
  move_together_app/lib/Photo/photos_screen.dart
  move_together_app/lib/Profile/profile_screen.dart
  move_together_app/lib/Trip/trip_join_screen.dart
  move_together_app/lib/Trip/trip_screen.dart
  move_together_app/lib/core/services/api.dart
  move_together_app/lib/router.dart
  move_together_app/lib/views/register_screen.dart
  move_together_app/pubspec.lock
  move_together_app/pubspec.yaml
Labels: flutter

#257 220 debug prod print everything till we know 1
  go/api/caca/caca.go
  go/api/handlers/trip.go
  go/api/utils/googleMapsWrapper.go
Labels: bug, go

#258 220 debug prod print everything till we know 1
  go/api/utils/googleMapsWrapper.go
Labels: bug, go

#259 220 debug prod print everything till we know 1
  go/api/caca/caca.go
  go/api/handlers/trip.go
  go/api/utils/googleMapsWrapper.go
Labels: bug, go, ci/k8s

#268 244 403 when deleting a photo that not belong and being the owner of the trip
  go/api/handlers/photo.go
  go/models/photo.go
  move_together_app/lib/Home/empty_home.dart
  move_together_app/lib/Home/home_screen.dart
Labels: flutter, go, ci/k8s

#269 fix(debug): remove prod debug
  go/api/utils/googleMapsWrapper.go
Labels: go

#270 feat(map): add default pos to map screen
  move_together_app/lib/Map/map_card.dart
  move_together_app/lib/Map/map_screen.dart
Labels: bug, flutter

#272 feat(photos): sort photo by creation date
  go/repository/photo.go
Labels: go

#274 fix(spam-qrcode): replaceName to home to stop the qrcode scan, add a …
  move_together_app/lib/Trip/trip_join_screen.dart
Labels: flutter

#278 fix: add currency formatting
  move_together_app/lib/Accommodation/accommodation_screen.dart
  move_together_app/lib/Activity/activity_screen.dart
  move_together_app/lib/Transport/transport_screen.dart
  move_together_app/lib/Trip/trip_cost_tag.dart
Labels: flutter

#276 fix(icons-not-centered): center icons and add a limit of 6 icons at a…
  move_together_app/lib/Trip/trip_app_bar.dart
  move_together_app/lib/Widgets/Participant/participant_icons.dart
Labels: flutter

#287 feat(file): add error snack when file to large
  go/api/handlers/document.go
  go/api/handlers/photo.go
  go/api/handlers/user.go
  move_together_app/lib/core/services/document_service.dart
  move_together_app/lib/core/services/photo_service.dart
  move_together_app/lib/core/services/user_service.dart
Labels: bug, flutter

#288 feat(flutter): translate error messages
  move_together_app/lib/Trip/trip_join_screen.dart
  move_together_app/lib/core/services/accommodation_service.dart
  move_together_app/lib/core/services/activity_service.dart
  move_together_app/lib/core/services/admin_service.dart
  move_together_app/lib/core/services/auth_service.dart
  move_together_app/lib/core/services/chat_service.dart
  move_together_app/lib/core/services/document_service.dart
  move_together_app/lib/core/services/feature_service.dart
  move_together_app/lib/core/services/note_service.dart
  move_together_app/lib/core/services/participant_service.dart
  move_together_app/lib/core/services/photo_service.dart
  move_together_app/lib/core/services/transport_service.dart
  move_together_app/lib/core/services/trip_service.dart
  move_together_app/lib/core/services/user_service.dart
  move_together_app/lib/views/login_screen.dart
  move_together_app/lib/views/register_screen.dart
Labels: flutter

#290 284 masquer le bouton de suppression dune photo si pas les droits
  move_together_app/lib/Photo/photo_card.dart
  move_together_app/lib/Photo/photo_info.dart
  move_together_app/lib/Photo/photo_item.dart
  move_together_app/lib/Photo/photos_screen.dart
  move_together_app/lib/Widgets/bottom_sheet_buttons.dart
Labels: bug, flutter

#291 283 refresh la liste des participant quand on close la modal avec le qr code
  move_together_app/lib/Home/home_screen.dart
  move_together_app/lib/Participant/participant_info.dart
Labels: flutter

#292 fix(create trip controller): add textcontroller listener for the butt…
  move_together_app/lib/Trip/trip_create_screen.dart
Labels: flutter

#296 293 test go
  .github/workflows/pr.yaml
  go/api/utils/geo/addressResolver_test.go
  go/go.mod
  go/go.sum
Labels: go
